create table if not exists public.customer_assets (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, site_id uuid null references public.sites(id) on delete set null, asset_name text not null, asset_type text null, manufacturer text null, model text null, serial_number text null, asset_tag text null, installed_date date null, warranty_until date null, location text null, status text not null default 'active' check (status in ('active','retired','lost','maintenance')), notes text null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists customer_assets_customer_idx on public.customer_assets(customer_id);
create unique index if not exists customer_assets_asset_tag_uq on public.customer_assets(asset_tag) where asset_tag is not null and asset_tag <> '';
create table if not exists public.service_contracts (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, service_id uuid null references public.services(id) on delete set null, contract_number text unique not null, name text not null, status text not null default 'active' check (status in ('draft','active','paused','expired','cancelled')), billing_interval text not null default 'monthly' check (billing_interval in ('monthly','quarterly','semi_annual','annual','one_time')), recurring_amount numeric not null default 0, start_date date not null default current_date, end_date date null, next_billing_date date null, auto_renew boolean not null default true, notes text null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists service_contracts_customer_idx on public.service_contracts(customer_id);
create sequence if not exists public.qvb_contract_number_seq;
create or replace function public.set_msp_updated_at() returns trigger language plpgsql security definer set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists customer_assets_set_updated_at on public.customer_assets; create trigger customer_assets_set_updated_at before update on public.customer_assets for each row execute function public.set_msp_updated_at();
drop trigger if exists service_contracts_set_updated_at on public.service_contracts; create trigger service_contracts_set_updated_at before update on public.service_contracts for each row execute function public.set_msp_updated_at();
alter table public.customer_assets enable row level security;
alter table public.service_contracts enable row level security;
drop policy if exists "CRM users can view customer assets" on public.customer_assets;
create policy "CRM users can view customer assets" on public.customer_assets for select to authenticated using (public.has_crm_permission('customers','view'));
drop policy if exists "CRM users can create customer assets" on public.customer_assets;
create policy "CRM users can create customer assets" on public.customer_assets for insert to authenticated with check (public.has_crm_permission('services','create'));
drop policy if exists "CRM users can update customer assets" on public.customer_assets;
create policy "CRM users can update customer assets" on public.customer_assets for update to authenticated using (public.has_crm_permission('services','update')) with check (public.has_crm_permission('services','update'));
drop policy if exists "Owner can delete customer assets" on public.customer_assets;
create policy "Owner can delete customer assets" on public.customer_assets for delete to authenticated using (public.has_crm_permission('services','delete'));
drop policy if exists "CRM users can view service contracts" on public.service_contracts;
create policy "CRM users can view service contracts" on public.service_contracts for select to authenticated using (public.has_crm_permission('services','view'));
drop policy if exists "CRM users can create service contracts" on public.service_contracts;
create policy "CRM users can create service contracts" on public.service_contracts for insert to authenticated with check (public.has_crm_permission('services','create'));
drop policy if exists "CRM users can update service contracts" on public.service_contracts;
create policy "CRM users can update service contracts" on public.service_contracts for update to authenticated using (public.has_crm_permission('services','update')) with check (public.has_crm_permission('services','update'));
drop policy if exists "Owner can delete service contracts" on public.service_contracts;
create policy "Owner can delete service contracts" on public.service_contracts for delete to authenticated using (public.has_crm_permission('services','delete'));
grant select, insert, update, delete on public.customer_assets, public.service_contracts to authenticated;
create or replace function public.next_service_contract_number() returns text language plpgsql security definer set search_path=public as $$ begin return 'CTR' || to_char(current_date,'YYYYMMDD') || lpad(nextval('public.qvb_contract_number_seq')::text,4,'0'); end; $$;
grant execute on function public.next_service_contract_number() to authenticated;